### ISSUE TITLE
SoftAssertion on assertj-db

### ISSUE THREAD

**Issue by willyhalim** [assertj/assertj-db#58]
Hi,

How do i do SoftAssertion proxy chaining for assertj-db ?

If i just proxy the RequestRowAssert i get issue like below
```

Exception in thread "main" org.assertj.db.exception.AssertJDBException: There is an exception 'org.assertj.db.api.RequestRowAssert.<init>(org.assertj.db.api.RequestAssert$ByteBuddy$lhIHVow8, org.assertj.db.type.Row)'
     in the instantiation of the element org.assertj.db.api.RequestRowAssert
     on class org.assertj.db.type.Row with class org.assertj.db.api.RequestAssert$ByteBuddy$lhIHVow8.
 It is normally impossible.
 That means there is a big mistake in the development of AssertJDB.
 Please write an issue for that if you meet this problem.
    at org.assertj.db.navigation.Position.getInstance(Position.java:117)
    at org.assertj.db.navigation.Position.getInstance(Position.java:91)
    at org.assertj.db.api.AbstractDbAssert.row(AbstractDbAssert.java:91)
    at org.assertj.db.api.RequestAssert$ByteBuddy$lhIHVow8.row$accessor$OIpnZ4B6(Unknown Source)
    at org.assertj.db.api.RequestAssert$ByteBuddy$lhIHVow8$AssertJ$SoftProxies$6PweGgTP.call(Unknown Source)
    at org.assertj.core.api.ErrorCollector.intercept(ErrorCollector.java:58)
    at org.assertj.db.api.RequestAssert$ByteBuddy$lhIHVow8.row(Unknown Source)
```

**Comment by VanRoy** [comment]
Implemented in release 1.3.0
